name: pre-commit_wsl

on:
  workflow_dispatch:
  pull_request:
  #push:
  #  branches: [exec]
  #  paths-ignore:
  #    - 'installation/constraints-*_*-wsl.txt'

jobs:
  pre-commit:
    runs-on: windows-2022
    strategy:
      matrix:
#        python-version: [ "3.12" ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13", "3.14" ]
        distribution: [ "Ubuntu-22.04", "Ubuntu-24.04" ]
      max-parallel: 1
    name: Pre-commit WSL python ${{ matrix.python-version }} dist ${{ matrix.distribution }}
    steps:
      - name: Bootstrapping dist ${{ matrix.distribution }}
        uses: Vampire/setup-wsl@v6
        with:
          distribution: ${{ matrix.distribution }}
          use-cache: 'true'
          update: 'true'
          additional-packages: |
            python3
            python3-pip
            build-essential
            libssl-dev
            zlib1g-dev
            libbz2-dev
            libreadline-dev
            libsqlite3-dev
            wget
            curl
            llvm
            libncurses5-dev
            libncursesw5-dev
            xz-utils
            tk-dev
            libffi-dev
            liblzma-dev
            python3-openssl
      - name: Cache pyenv and pip in WSL
        id: cache-pyenv
        uses: actions/cache@v5
        with:
          path: |
            .pyenv
            .bash_profile
            .bashrc
            .cache/pip
          key: ${{ runner.os }}-${{ matrix.python-version }}-${{ matrix.distribution }}
      - name: Install pyenv in WSL
        if: steps.cache-pyenv.outputs.cache-hit != 'true'
        shell: wsl-bash {0}
        run: |
          pwd
          ls -la
          git clone -b v2.6.11 https://github.com/pyenv/pyenv.git ~/.pyenv
          cd ~/.pyenv && src/configure && make -C src
          
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
          echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
          echo 'eval "$(pyenv init - bash)"' >> ~/.bashrc
          
          echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
          echo '[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bash_profile
          echo 'eval "$(pyenv init - bash)"' >> ~/.bash_profile
      - name: Install python ${{matrix.python-version}} using pyenv in WSL
        if: steps.cache-pyenv.outputs.cache-hit != 'true'
        shell: wsl-bash {0}
        run: |
          source ~/.bash_profile
          pyenv install ${{matrix.python-version}}
          pyenv global ${{matrix.python-version}}
      - name: Clone repo
        shell: wsl-bash {0}
        run: |
          git clone --filter=blob:none --no-checkout "${{github.server_url}}/${{github.repository}}" the_repo
          cd the_repo
          git checkout "${{github.sha}}"
      - name: 'Install requirements (standard or constraints ${{ matrix.python-version }})'
        shell: wsl-bash {0}
        run: |
          source ~/.bash_profile
          cd the_repo
          python -mvenv .env
          source .env/bin/activate
          
          pip install --upgrade pip wheel
          constraints_file="installation/constraints-${{ matrix.python-version }}_${{ matrix.distribution }}-wsl.txt"
          regen_constraints=
          if [ -f "$constraints_file" ] ; then
            at="$(git --no-pager log -p -1 "--format=tformat:%at" --no-patch -- "$constraints_file")"
            dat="$(git --no-pager log -p -1 "--format=tformat:%at" --no-patch -- "installation/requirements.txt")"
            if [ "$at" -lt "$dat" ] ; then
              regen_constraints=true
            fi
          else
            regen_constraints=true
          fi
          if [ -n "$regen_constraints" ] ; then
            pip install -r installation/requirements.txt
            pip freeze > "$constraints_file"
            grep -vF git+ "$constraints_file" > "$constraints_file"-relaxed
          else
            grep -vF git+ "$constraints_file" > "$constraints_file"-relaxed
            pip install -r installation/requirements.txt -c "$constraints_file"-relaxed
          fi
      - name: 'Install development requirements'
        shell: wsl-bash {0}
        run: |
          source ~/.bash_profile
          cd the_repo
          source .env/bin/activate
          
          pip install -r installation/dev-requirements.txt -r installation/mypy-requirements.txt -c installation/constraints-${{ matrix.python-version }}_${{ matrix.distribution }}-wsl.txt-relaxed
#      - name: MyPy cache
#        uses: actions/cache@v5
#        with:
#          path: '.mypy_cache/[0-9]*'
#          key: mypy-${{ matrix.python-version }}
      - name: 'pre-commit'
        shell: wsl-bash {0}
        run: |
          source ~/.bash_profile
          cd the_repo
          source .env/bin/activate
          
          pre-commit run -a
      - name: CPU database cache restore
        id: cache-cpu-databases-restore
        uses: actions/cache/restore@v5
        with:
          path: |
            the_repo/cpumark_table.csv
            the_repo/cpu-spec-dataset
          key: cpu_databases_wsl
      - name: CPU database population
        if: steps.cache-cpu-databases-restore.outputs.cache-hit != 'true'
        shell: wsl-bash {0}
        run: |
          source ~/.bash_profile
          cd the_repo
          source .env/bin/activate
          
          python -m treecript.tdp_sources cpumark_table.tsv
          git clone https://github.com/JosuaCarl/cpu-spec-dataset
      - name: CPU database cache save
        if: steps.cache-cpu-databases-restore.outputs.cache-hit != 'true'
        id: cache-cpu-databases-save
        uses: actions/cache/save@v5
        with:
          path: |
            the_repo/cpumark_table.csv
            the_repo/cpu-spec-dataset
          key: ${{ steps.cache-cpu-databases-restore.outputs.cache-primary-key }}
      - name: 'pytest + coverage (${{ matrix.python-version }})'
        shell: wsl-bash {0}
        run: |
          source ~/.bash_profile
          cd the_repo
          source .env/bin/activate
          
          CACHED_CPU_SPEC_DATASET=${PWD}/cpu-spec-dataset CACHED_CPUMARK_DATASET=${PWD}/cpumark_table.tsv  pytest --cov=treecript
      - uses: actions/upload-artifact@v6
        with:
          name: wsl_pre-commit-${{ matrix.python-version }}_${{ matrix.distribution }}
          retention-days: 2
          path: the_repo/installation/constraints-${{ matrix.python-version }}_${{ matrix.distribution }}-wsl.txt

  check_licences:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        python-version: [ "3.12" ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13", "3.14" ]
        distribution: [ "Ubuntu-22.04", "Ubuntu-24.04" ]
    name: Validate licences of gathered dependencies (WSL python ${{ matrix.python-version }} dist ${{ matrix.distribution }})
    needs:
      - pre-commit
    steps:
      - name: Get analysis timestamp
        id: timestamp
        run: echo "timestamp=$(date -Is)" >> "$GITHUB_OUTPUT"
      - uses: actions/download-artifact@v7
        id: download
        with:
          name: wsl_pre-commit-${{matrix.python-version}}_${{ matrix.distribution }}
      - name: Get transitive dependencies licences
        id: license_check_print_report
#        continue-on-error: true
        uses: pilosus/action-pip-license-checker@v3.1.0
        with:
          requirements: installation/constraints-${{ matrix.python-version }}_${{ matrix.distribution }}-wsl.txt
#      - name: Check transitive dependencies licences
#        id: license_check_report
#        uses: pilosus/action-pip-license-checker@v3.1.0
#        with:
#          requirements: installation/constraints-${{ matrix.python-version }}.txt
#          fail: 'StrongCopyleft'
#          exclude: '(?i)^(pylint|dulwich|docutils).*'
      - name: Print licences report
        if: ${{ always() }}
        run: echo "${{ steps.license_check_print_report.outputs.report }}"

  pull_request_changes:
    # Do this only when it is not a pull request validation
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    name: Pull request with the newly generated contents
    needs:
      - check_licences
    steps:
      - name: Get analysis timestamp
        id: timestamp
        run: echo "timestamp=$(date -Is)" >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7
        id: download
        with:
          pattern: wsl_pre-commit-*_*
          merge-multiple: true
          path: changes-dir
      - name: Move artifacts to their right place
        id: move
        run: |
          skip=true
          if [ -d "${{steps.download.outputs.download-path}}" ] ; then
            for con in "${{steps.download.outputs.download-path}}"/installation/constraints-*_*-wsl.txt ; do
              case "$con" in
                */constraints-\*_\*-wsl.txt)
                  break
                  ;;
                *)
                  cp -p "$con" installation
                  skip=false
                  ;;
              esac
            done
          fi
          echo "skip=$skip" >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v8
        if: steps.move.outputs.skip == 'false'
        with:
          title: Updated WSL constraints (triggered on ${{ steps.timestamp.outputs.timestamp }} by ${{ github.sha }})
          branch: create-pull-request/patch-wsl_constraints
          add-paths: installation/constraints-*_*-wsl.txt
          delete-branch: true
          commit-message: "[create-pull-request] Automatically commit updated contents (constraints WSL)"
      - name: Check outputs
        if: ${{ steps.cpr.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}" >> "$GITHUB_STEP_SUMMARY"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}" >> "$GITHUB_STEP_SUMMARY"
